server:
  port: 8181
spring:
  application:
    name: login-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydb
  zipkin:
    base-url: http://localhost:9411             
  config:
    import:
     configserver:http://localhost:8888  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
management:
  endpoints:
    web:
      exposure:
        include: "*" 
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true         