server:
  port: 8888
spring:
  application:
    name: configuration-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/nagaraju022/olx-config
          default-label: main
          username: nagaraju022
          password: Smart@4400
          clone-on-start: true


        