server:
  port: 9090
spring:
  application:
    name: masterdata-service
  config:
    import:
     configserver:http://localhost:8888
  zipkin:
    base-url: http://localhost:9411
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true   
    